### PR TITLE
iCloud China Support

### PR DESCRIPTION
**Pull request by Sowevo**
#286 
Added **icloud-china** option
> Use icloud.com.cn instead of icloud.com as the download source.

I only tested the `token ` and `sync` of my Chinese iCloud account
He works fine and successfully downloads my photos (with some warnings ⚠️)
image

### CODE REVIEW

**Comment by steilerDev** [comment]
Thank you very much for this PR!

Do we know that only China has this special behaviour (i.e. a 'region' setting that would be more extensible could make more sense if there are other regions that have a similar behaviour)

Additionally: Could you please add some unit tests to ensure that we will not have any regression moving forward?

**Comment by steilerDev** [comment]
Please ignore the CI runs - I just realized that it's trying to run tests that require access to the secrets - I will fix this in a bit.

**Comment by steilerDev** [comment]
c715f59 should fix PR logic

**Comment by Sowevo** [comment]
> Do we know that only China has this special behaviour (i.e. a 'region' setting that would be more extensible could make more sense if there are other regions that have a similar behaviour)


I think only China has this special behavior, refer to the processing of other iCloud repository

**Comment by Sowevo** [comment]
> Additionally: Could you please add some unit tests to ensure that we will not have any regression moving forward

Thank you for reviewing my code changes. I wanted to let you know that I haven't had much experience with Node.js projects in the past, so I might not be able to write unit tests as requested.🥹

**Comment by steilerDev** [comment]
Give it a try - this is my first node project that runs unit tests as well - need to start somewhere ;)

Otherwise merging of this will need to wait a bit

**Comment by Sowevo** [comment]
I'll give it a try, give me some time.

**Pull request closed without merging**
